name: Lint

on:
  push:
    paths:
      - '**.py'

  pull_request:
    types: [opened, reopened, ready_for_review, review_requested]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Lint check ruff
        uses: chartboost/ruff-action@v1
